services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_catalogo_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345678" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  sonarqube-db:
    image: postgres:13
    platform: linux/amd64
    container_name: sonarqube-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sonar -d sonarqube" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  sonarqube:
    image: sonarqube:9.9.5-community
    platform: linux/amd64
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      sonarqube-db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    networks:
      - appnet
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  backend-catalogo:
    platform: linux/amd64
    container_name: backend-catalogo
    restart: unless-stopped
    build:
      context: ./backend-catalogo
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_catalogo_ci
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend-catalogo:
    platform: linux/amd64
    container_name: frontend-catalogo
    restart: unless-stopped
    build:
      context: ./frontend-catalogo
    depends_on:
      backend-catalogo:
        condition: service_started
    ports:
      - "8082:80"
    networks:
      - appnet

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    user: root
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    networks:
      - appnet

volumes:
  mysql_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db:
  jenkins_home:

networks:
  appnet:
    driver: bridge