services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_catalogo_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  backend-catalogo:
    platform: linux/amd64
    build:
      context: ./backend-catalogo
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_catalogo_ci
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend-catalogo:
    platform: linux/amd64
    build:
      context: ./frontend-catalogo
    ports:
      - "8082:80"
    depends_on:
      - backend-catalogo
    networks:
      - appnet

  jenkins:
    image: jenkins/jenkins:lts
    platform: linux/amd64
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y curl &&
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&
        apt-get install -y nodejs &&
        apt-get install -y docker.io &&
        exec /usr/local/bin/jenkins.sh
      "

  sonarqube:
    image: sonarqube:9.9.5-community
    platform: linux/amd64
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - appnet

volumes:
  mysql_data:
  jenkins_home:

networks:
  appnet:
    driver: bridge