name: productcatalogo_ngspring
services:
  mysql:
    ports: []
  sonarqube-db:
    ports: []
  sonarqube:
    ports: []
  backend-catalogo:
    ports: []
  frontend-catalogo:
    ports: []
  jenkins:
    ports: []
