services:
  backend-catalogo:
    build: ./backend-catalogo
    ports:
      - "8080:8080"
    volumes:
      - catalogo_data:/data
    networks:
      - appnet

  frontend-catalogo:
    build: ./frontend-catalogo
    ports:
      - "4200:80"
    depends_on:
      - backend-catalogo
    networks:
      - appnet

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet

volumes:
  catalogo_data:
  jenkins_home:

networks:
  appnet:
    driver: bridge